export const planos = [
  {
    name: "Free",
    description: "Para começar a treinar e conhecer a plataforma.",
    price: "R$ 0",
    period: "",
    caption: "Acesso gratuito.",
    button: "Começar grátis",
    highlighted: false,
    dark: false,
    features: [
      "Simulados limitados",
      "Desempenho básico",
      "Histórico simples",
      "Painel do aluno",
    ],
  },
  {
    name: "Pro",
    description: "Para estudar com mais constância e direção.",
    price: "R$ 29",
    period: "/mês",
    caption: "Ideal para rotina individual.",
    button: "Assinar Pro",
    highlighted: false,
    dark: false,
    features: [
      "Simulados ilimitados",
      "Trilhas recomendadas",
      "Relatórios por matéria",
      "Revisão por pontos fracos",
    ],
  },
  {
    name: "Premium",
    description: "Para uma preparação mais completa e inteligente.",
    price: "R$ 49",
    period: "/mês",
    caption: "Mais análise e mais precisão.",
    button: "Assinar Premium",
    badge: "Mais completo",
    highlighted: true,
    dark: false,
    features: [
      "Tudo do plano Pro",
      "Correção de redação com IA",
      "Análises avançadas",
      "Recomendações inteligentes",
    ],
  },
  {
    name: "Enterprise",
    description: "Para escolas, cursinhos e instituições.",
    price: "Custom",
    period: "",
    caption: "Valor por instituição.",
    button: "Solicitar proposta",
    highlighted: false,
    dark: true,
    features: [
      "Gestão de alunos e turmas",
      "Simulados próprios",
      "Relatórios institucionais",
      "Área para coordenação",
    ],
  },
];
